### ISSUE TITLE
java.lang.IllegalArgumentException when accessing configuration properties

### ISSUE THREAD

**Issue by Kornel** [npryce/konfig#6]
Hi,

the stacktrace is:

```
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.JvmClassMappingKt.getKotlinClass, parameter $receiver
    at kotlin.jvm.JvmClassMappingKt.getKotlinClass(JvmClassMapping.kt)
    at com.natpryce.konfig.PropertyGroup.outer(magic.kt:16)
    at com.natpryce.konfig.PropertyGroup.namePrefix(magic.kt:18)
    at com.natpryce.konfig.PropertyGroup.name(magic.kt:17)
    at com.natpryce.konfig.PropertyGroup.key(magic.kt:23)
    at com.natpryce.konfig.MagicKt.getValue(magic.kt:28)

```

I took a look at the code and there is a silent requirement for the configuration class to be inside another class:

```
open class PropertyGroup(private val outer: PropertyGroup? = null) : PropertyKeys() {
    private fun outer() = outer ?: javaClass.enclosingClass.kotlin.objectInstance as? PropertyGroup

```

If the configuration object is a top level class in a separate file, javaClass.enclosingClass is null. This is the case in all the tests, btw, that the config object is inside an other class (eg.: https://github.com/npryce/konfig/blob/master/src/test/kotlin/com/natpryce/konfig/magic_tests.kt#L19)  However it's not obvious from the README.md that it is a requirement.

I'm wondering how to fix this - I guess it should not be necessary to require a top level class, however I might be missing something. 

Either the documentation should be updated or the code :)

**Comment by ccampo133** [comment]
Any chance we could get the above PR merged, or is this project dead?

**Comment by npryce** [comment]
Merged.
